//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JsonProjectDataBseNewEntities : DbContext
    {
        public JsonProjectDataBseNewEntities()
            : base("name=JsonProjectDataBseNewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<CompetitionResult> CompetitionResults { get; set; }
        public virtual DbSet<OlympicSport> OlympicSports { get; set; }
        public virtual DbSet<TableOfUser> TableOfUsers { get; set; }
    }
}
